version: '3'
networks:
  sdp:
    driver: bridge
services:
  jenkins:
    networks:
      - sdp
    privileged: true
    user: root
    container_name: sdp-jenkins
    image: jenkins/jenkins:2.138.3
    build:
      context: ./docker/jenkins
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    links:
      - sonarqube
      - registry
  sonarqube:
    networks:
      - sdp
    container_name: sdp-sonarqube
    image: sonarqube:latest
    build:
      context: ./docker/sonarqube
      dockerfile: Dockerfile
    ports:
    - 9000:9000
    - 9092:9092
  registry:
    networks:
      - sdp
    container_name: sdp-registry
    image: registry:2
    ports:
    - 5000:5000
  sonar-scanner:
    networks:
      - sdp
    container_name: sonar-scanner
    image: sdp/sonar-scanner:latest
    build:
      context: ./docker/sonar-scanner
      dockerfile: Dockerfile
    depends_on:
    - sonarqube
